# Generated by Django 5.2.3 on 2025-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoSocial", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "wood_type",
                    models.CharField(
                        choices=[
                            ("pallet", "Pallet"),
                            ("plank", "Plank"),
                            ("offcut", "Offcut"),
                        ],
                        max_length=20,
                    ),
                ),
                ("size", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="stock_images/"),
                ),
                ("description", models.TextField(blank=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
